### ISSUE TITLE
Schema not shown for optional methods

### ISSUE THREAD

**Issue by Rotzbua** [raml2html/raml2html#187] opened 2016-03-24 14:48 UTC
Hi, I use optional methods in resourceTypes. For response I define schema, but it is not shown correctly. Only for non optional methods it is shown correctly.

Here my example:
```raml
#%RAML 0.8
title: test
mediaType: application/json

schemas:
  - testschema: |
      content of schema

resourceTypes:
  - collectionbug:
      get?:
        responses:
          200:
            body:
              schema: testschema
  - collection:
      get:
        responses:
          200:
            body:
              schema: testschema

/booksbug:
  type: collectionbug
  get:

/books:
  type: collection
  get:
```
For /booksbug I get incorrect schema, seems not resolved:
```
Type: schema
```
For /books I get correct schema:
```
Type: application/json
Schema:
content of schema
```

Did I misunderstood the raml spec or is it a bug?

**Comment by nmors** [comment] 2016-04-01 00:45
duplicate of #188

**Closed** 2016-10-04 14:58 UTC
