### ISSUE TITLE
Data types with many union type attributes blow up memory usage

### ISSUE THREAD

**Issue by rmihael** [raml2html/raml2html#326] opened 2017-02-13 14:26 UTC
When trying to build HTML documentation from my RAML using raml2html 4.1.1 I'm getting out of memory error.

Version 4.0.6. works fine on the same file. 

I'm attaching minimal file that reproduce the problem. It seems that total number of attributes in `SomeProfile` matters. By commenting out about half of them I can make raml2html work. Replacing `string?` with `sting` also helps.
[api.raml.zip](https://github.com/raml2html/raml2html/files/771316/api.raml.zip)

```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 5: v8::internal::Factory::NewFixedArray(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 6: v8::internal::TypeFeedbackVector::New(v8::internal::Isolate*, v8::internal::Handle<v8::internal::TypeFeedbackMetadata>) [/usr/local/bin/node]
 7: v8::internal::SharedFunctionInfo::FindOrCreateLiterals(v8::internal::Handle<v8::internal::SharedFunctionInfo>, v8::internal::Handle<v8::internal::Context>) [/usr/local/bin/node]
 8: v8::internal::JSFunction::EnsureLiterals(v8::internal::Handle<v8::internal::JSFunction>) [/usr/local/bin/node]
 9: v8::internal::Compiler::Compile(v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Compiler::ClearExceptionFlag) [/usr/local/bin/node]
10: v8::internal::Runtime_CompileLazy(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
11: 0x1832f8f063a7
12: 0x1832f8f0675a
13: 0x1832fab0ab31
14: 0x1832faa2c9cb
15: 0x1832fab258e4
Abort trap: 6
```

**Comment by kevinrenskers** [comment] 2017-02-13 14:30
Hmm I'm guessing it's caused by the updated raml-1-parser but we'll need to look into it. Thanks for the report!

**Comment by rmihael** [comment] 2017-02-13 23:13
Just checked, reproduces on 5.0.0.

**Comment by kevinrenskers** [comment] 2017-02-13 23:15
Yeah that would not have changed anything since they both use the same parser under the hood.

**Comment by kevinrenskers** [comment] 2017-02-13 23:17
@sichvoge do you happen to know if there are memory problems with raml-1-parser 1.1.13? We updated from 1.1.9 to 1.1.13 recently.

**Comment by sichvoge** [comment] 2017-02-14 03:49
Not as far as I know! I'll ask the team to investigate.

**Comment by nickwb** [comment] 2017-02-14 07:32
On the surface, this feels a little similar to this: https://github.com/raml2html/raml2obj/issues/28

Although @rmihael is not using datatype-expansion 0.1.1, I would not be surprised to discover he is running out of memory during `expandedForm` or `canonicalForm`.

**Comment by KonstantinSviridov** [comment] 2017-02-14 14:18
Hi everyone

I've tried to find out whether the issue is on the parser side or not, and it appears, that the issue is inside the `raml2obj` module used by `raml2html`.

Here are my actions.

* I installed `raml2html` globally and tried to apply it to the example raml. As a result, it hung.

* Then I modified `raml2obj` module used by `raml2html` in the following manner:
In https://github.com/raml2html/raml2obj/blob/master/index.js#L165-L167
I modified the main exported function in order to examine outputs of the parser and raml2obj:
```
module.exports.parse = function (source) {
  return _sourceToRamlObj(source).then(ramlObj => {
    fs.writeFileSync(path.resolve(__dirname,"dump1.json"),JSON.stringify(ramlObj,null,2));
    var result = _enhanceRamlObj(ramlObj);
    fs.writeFileSync(path.resolve(__dirname,"dump2.json"),JSON.stringify(result,null,2));
    return result;
  });
};
```

* As a result, I found `dump1.json` (which looks fine) in the `raml2obj` module directory, but I did not see `dump2.json` there. Thus, the issue is inside `raml2obj`.

I've also tried processing the example raml with `develop` parser and `1.1.13` published parser. Both experiments ended fine.

**Comment by nickwb** [comment] 2017-02-14 14:22
Thanks, @KonstantinSviridov

**Comment by kevinrenskers** [comment] 2017-02-15 10:21
I tested this file with raml-1-parser version 1.1.9 and that did indeed not make any difference. So then I went deeper to find the cause, and it's definitely within the `_expandRootTypes` function in raml2obj. If you comment out the whole bit where `tools.expandedForm` is called, then you won't get this memory problem. It seems to me that the memory issue is caused by the `datatype-expansion` library, but it doesn't make sense that ram2html 4.0.6 works fine since this dependency has not changed at all.

So I tried to parse this same RAML file with raml2obj 4.0.4 and even 4.0.0 with no luck. Same memory problem, so I really doubt this file worked with raml2html 4.0.6. Just to make sure, I went back to raml2html 4.0.6 and yeah, I am not getting this RAML file parsed with that version either.

It's definitely a problem with the  `datatype-expansion` library.

**Comment by kevinrenskers** [comment] 2017-02-15 10:27
I created a new issue here: https://github.com/raml-org/raml-parser-toolbelt/issues/49. I am going to close this issue since it's sadly not a problem we can fix on our end :(

**Comment by rmihael** [comment] 2017-02-15 10:28
Sorry for confusion. 4.0.6. worked for my original documentation from where I managed to extract this small proof-case. For whatever reason 4.0.6 not working on it for me as well.

**Closed** 2017-02-15 10:28 UTC

**Comment by sichvoge** [comment] 2017-02-15 14:47
Thanks @kevinrenskers. We have a full backlog this week, but we'll look at it next week. Sorry about the delay
