### ISSUE TITLE
CDN resources blocked

### ISSUE THREAD

**Issue by zebronics** [raml2html/raml2html#376] opened 2017-12-26 10:20 UTC
Recently the google  search console  reported that my sites CDN version : https://cdn.zebronics.com under blocked resources.

Also in page speed insights it shows the below result with all issues on the CDN
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fzebronics.com%2F

**Comment by kevinrenskers** [comment] 2017-12-26 10:43
I'm sorry, but I have no clue what you mean or what the problem is? How is cdn.zebronics.com related to the raml2html project?

**Comment by zebronics** [comment] 2017-12-26 10:59
I think i placed it under wrong category.

I am having issue with the website cdn as i mentioned above.

Could know the best place for solution.

**Comment by kevinrenskers** [comment] 2017-12-26 11:02
> I am having issue with the website cdn

Yes but how is that related to raml2html?

Closing this issue, doesn't seem related at all.

**Closed by kevinrenskers** 2017-12-26 11:02 UTC
