### ISSUE TITLE
Inherited properties are not rendered if there is a property of type array

### ISSUE THREAD

**Issue by lijithv** [raml2html/raml2html#280] opened 2016-11-25 02:09 UTC
raml2html version : **4.0.0-beta17**

I have the following raml file with Customer type which inherits properties from CommonBase type. Unfortunately, inherited properties doesn't seem to render when there is a property (Addresses) of type array. If I remove the addresses array, the inherited properties are rendered as expected. 

```
#%RAML 1.0
title: sample-api
version: v0.1
baseUri: http://api.samplehost.com
types:
  CommonBase:
    type: object
    properties:
      id: string
      eTag: string
  Address :
    type: object
    required: false
    properties:
      addressType:
        enum: ['postal', 'business']
      line1: string
      line2?: string
      suburb: string
      postcode: number
  Customer:
    type: CommonBase
    properties:
      name: string
      age:
        type: number
        required: false
      email?: string
      mobile?: string
      addresses:
        type: array
        items:
          type: Address
/customers:
  get:
    responses:
      200:
        body:
          application/json:
            type: array
            items:
              type: Customer
            example: |
              [{
                "id" : "ID124",
                "eTag": "13298308323",
                "name" : "Smith",
                "age" : 30,
                "addresses" : [{
                  "addressType" : "postal",
                  "line1" : "Walker Street",
                  "suburb" : "Sydney",
                  "postcode" : 1234
                  }]
              }]

```
I have attached the sample files with and without using array and their outputs. 
[array-and-inheritance.zip](https://github.com/raml2html/raml2html/files/612361/array-and-inheritance.zip)

Thank you.

**Comment by psychoo118** [comment] 2017-02-03 08:50
I checked the example you provided and I can confirm that the issue exists. The problem lies in raml2obj or to be more precise: in its dependency, datatype-expansion. This library is used to resolve type inheritances so raml2obj don't need to work with references to super types. For some reason this dependency throws an error when it starts processing the Customer type so its supers won't be resolved.

@kevinrenskers As I can see version 0.0.15 is fixed in raml2obj for datatype-expansion dependency. I checked the example provided by @lijithv with a newer version(0.1.1) and it seems like the problem is gone. Running tests result in only one fail. What do you think, can we upgrade datatype-expansion in raml2obj?

**Comment by lijithv** [comment] 2017-02-03 09:11
Thanks @psychoo118 for the update

**Comment by kevinrenskers** [comment] 2017-02-03 09:35
@psychoo118 check out this issue I created yesterday: https://github.com/raml2html/raml2obj/issues/28. "Running tests result in only one fail", so let's fix that test :)

**Comment by kevinrenskers** [comment] 2017-02-03 09:36
(or if it's a bug in datatype-expansion that causes our failing test, report it upstream)

**Comment by psychoo118** [comment] 2017-02-03 10:36
oops I dont know how the hell I missed your issue. Okay I will check that fail tonight or tomorrow.

**Comment by kevinrenskers** [comment] 2017-03-17 11:53
Can you please test again with 6.0.0?

**Comment by lijithv** [comment] 2017-03-17 12:09
@kevinrenskers, I re-tested this issue with the latest raml2html 6.0.0 but the issue is still happening.

**Comment by kevinrenskers** [comment] 2017-03-17 12:10
Yeah sorry I realized that it's because of the external datatype-expansion library, which we can't update yet.

**Comment by lijithv** [comment] 2017-03-17 12:12
Thats alright. Thank you for the update.

**Comment by kevinrenskers** [comment] 2018-09-13 17:03
Closing due to inactivity.

**Closed by kevinrenskers** 2018-09-13 17:03 UTC
