### ISSUE TITLE
graceful-fs@2 and @3 support will be removed soon

### ISSUE THREAD

**Issue by ChALkeR** [raml2html/raml2html#234] opened 2016-07-24 04:25 UTC
Hi. `raml2html` is currently `#49` in my [list of modules](https://gist.github.com/ChALkeR/d39b49642e02277d2292d66c2ea0bced) that would likely to be broken when https://github.com/nodejs/node/pull/6413 lands (which is anticipated to happen before v7.0).

Note that `graceful-fs@1` and `graceful-fs@4` are ok and would not be broken by this, but a `require()` on `graceful-fs@2` or `graceful-fs@3` would cause an error soon.

That is, runtime warning `fs: re-evaluating native module sources is not supported.` would be turned into a throw.

If you or your deps use `graceful-fs@2` or `graceful-fs@3` in runtime — you are affected. 

Tracking: https://github.com/nodejs/node/issues/5213.

**Comment by sichvoge** [comment] 2016-07-25 11:15
Thanks for letting us know @ChALkeR. We will see what we can do on that.

**Comment by kevinrenskers** [comment] 2016-08-04 15:47
raml2html actually doesn't directly depend on graceful-fs, so it has to be one of our dependencies, or some layers deep within their dependencies. Let's start with finding out which of our direct deps is the cause.

**Comment by ChALkeR** [comment] 2016-08-04 15:56
@kevinrenskers You can do that with `npm list graceful-fs`.

**Comment by kevinrenskers** [comment] 2016-08-04 16:01
It's nunjucks 1.3.4 that depends on chokidar 0.1.2.6 which depends on readdirp 1.3.0 which depends on graceful-fs 2.0.3.

![screen shot 2016-08-04 at 17 58 41](https://cloud.githubusercontent.com/assets/229384/17408947/732ae72a-5a6d-11e6-8935-f0c9ad015105.png)

Pretty cool tool:
http://npm.anvaka.com/#/view/2d/raml2html

**Comment by kevinrenskers** [comment] 2016-08-04 16:02
We'll be updating nunjucks in the next version of raml2html so that should hopefully fix this problem.

**Comment by kevinrenskers** [comment] 2016-08-07 12:23
raml2html 3.0.0-beta was just released which solves this problem. Once it's tested it will be released as 3.0.0. 

Closing this ticket now, thanks @ChALkeR for pointing us to the problem.

**Closed by kevinrenskers** 2016-08-07 12:23 UTC
Labels: bug
